[profile.default]
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib']
test = 'test'
cache_path  = 'cache_forge'
verbosity = 2
evm_version = 'shanghai'

[rpc_endpoints]
base = "${BASE_URL}"
optimism = "${OPTIMISM_URL}"
arbitrum = "${ARBITRUM_URL}"
polygon = "${POLYGON_URL}"

[etherscan]
base = { key = "${BASE_ETHERSCAN_API_KEY}" }
optimism = { key = "${OPTIMISM_ETHERSCAN_API_KEY}" }
arbitrum = { key = "${ARBITRUM_ETHERSCAN_API_KEY}" }
polygon = { key = "${POLYGON_ETHERSCAN_API_KEY}" }
