name: Run Basic Checks

on:
  pull_request:
    branches:
      - master
    types:
      - opened
      - synchronize

jobs:
  checks:
    name: Compiling, Linting, Unit Testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: ^8.0.0
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "pnpm"
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile
        working-directory: ./
      - name: Lint
        run: pnpm lint
      - name: Check formatting
        run: pnpm prettier:check
      - name: Test (Unit)
        run: pnpm test:unit
